### ISSUE TITLE
Issue package for `decimal.NullDecimal` not imported

### ISSUE THREAD

**Issue by edyulianto** [sog01/repogen#5]
Hi Mr.@sog01, I have found unimported package for NullDecimal.
<img width="601" alt="image" src="https://user-images.githubusercontent.com/10769164/170402744-66db4080-5f3e-4bdd-a113-b09762cf17f2.png">
Do we need to add validation if it's type null decimal in the following line?
https://github.com/sog01/repogen/blob/f6e4072288d712ad99614a3fa2ced3ae453e1e19/parser/gostruct.go#L136-L137

**Comment by sog01** [comment]
Thanks for the reported @edyulianto, I think you're right!

For the fast fix we just need to reorder the condition of `decimal` string contains into the top level :
```
if strings.Contains(strings.ToLower(string(field.Type)), "decimal") {
	importedMap["github.com/shopspring/decimal"] = struct{}{}
} else if strings.Contains(strings.ToLower(string(field.Type)), "null") {
	importedMap["github.com/guregu/null"] = struct{}{}
} else if strings.Contains(strings.ToLower(string(field.Type)), "time") {
	importedMap["time"] = struct{}{}
}
```

Will try to fix this ASAP, again thanks for the report!

**Comment by sog01** [comment]
This issue already fixed on this PR https://github.com/sog01/repogen/pull/6. Please pull the latest version to apply this fix changes @edyulianto.

p.s. If you still have any issue or feedback, please don't hesitate to ping again!

**Comment by edyulianto** [comment]
Thank you very much Mr.@sog01
